<!DOCTYPE html>
<html>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .title {
            font-size: 18px;
            font-weight: bold;
        }

        .subtitle {
            font-size: 14px;
            margin-top: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #000;
            padding: 5px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title">{{ $title }}</div>
        <div class="subtitle">{{ __('Generated by') }}: {{ $username }}</div>
        <div class="subtitle">{{ __('Date') }}: {{ now()->format('Y-m-d H:i') }}</div>
    </div>

    <h3>{{ __('Booking Information') }}</h3>
    <table>
        <tr>
            <th>{{ __('Reservation Day') }}</th>
            <th>{{ __('Booking Date') }}</th>
            <th>{{ __('Start Time') }}</th>
            <th>{{ __('End Time') }}</th>
            <th>{{ __('Cruise Type') }}</th>
            <th>{{ __('Boat Name') }}</th>
        </tr>
        <tr>
            <td>{{ __(WEEK_DAYES[$data['booking']->booking_date->dayOfWeek]) }}</td>
            <td>{{ $data['booking']->booking_date->format('Y-m-d') }}</td>
            <td>{{ $data['booking']->start_time->format('H:i') }}</td>
            <td>{{ $data['booking']->end_time->format('H:i') }}</td>
            <td>{{ $data['booking']->type->name }}</td>
            <td>{{ $data['booking']->sailing_boat->name }}</td>
        </tr>
    </table>

    <h3>{{ __('Booking Groups') }}</h3>
    <table>
        <thead>
            <tr>
                <th>{{ __('Name') }}</th>
                <th>{{ __('Serial No.') }}</th>
                <th>{{ __('Total Members') }}</th>
                @foreach ($data['clientTypes'] as $type)
                    <th>{{ $type->name }}</th>
                @endforeach
                <th>{{ __('Paid') }}</th>
                @foreach ($data['paymentMethods'] as $method)
                    <th>{{ $method->name }}</th>
                @endforeach
                <th>{{ __('Remain') }}</th>
                <th>{{ __('Total') }}</th>
                <th>{{ __('Phone') }}</th>
                <th>{{ __('Client Supplier') }}</th>
                <th>{{ __('Notes') }}</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($data['booking']->booking_groups as $group)
                <tr>
                    <td>{{ $group->client->name }}</td>
                    <td>{{ $group->booking_group_num }}</td>
                    <td>{{ $group->total_members }}</td>
                    @foreach ($data['clientTypes'] as $type)
                        <td>
                            @php
                                $count = $group->booking_group_members
                                    ->where('client_type_id', $type->id)
                                    ->sum('members_count');
                            @endphp
                            {{ $count === 0 ? '0' : $count }}
                        </td>
                    @endforeach
                    <td>{{ $group->paid === 0 ? '0' : $group->paid }}</td>
                    @foreach ($data['paymentMethods'] as $method)
                        <td>
                            @php
                                $amount = $data['paymentAmounts'][$group->id][$method->id] ?? 0;
                            @endphp
                            {{ $amount === 0 ? '0' : $amount }}
                        </td>
                    @endforeach
                    <td>{{ $group->remain == 0 ? '0' : $group->remain }}</td>
                    <td>{{ $group->total == 0 ? '0' : $group->total }}</td>
                    <td>{{ $group->client->phone }}</td>
                    <td>{{ $group->client_supplier->name ?? '-' }}</td>
                    <td>{{ $group->notes ?? '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</body>

</html>
