@push('css')
<link href="{{asset('assets/admin')}}/plugins/select2/css/select2.min.css" rel="stylesheet">
<style>
	select {
		font-family: 'Font Awesome 5 Pro' , "Font Awesome 5 Brands" !important
	}
    .fas{
        font-family: 'Font Awesome 5 Pro' , "Font Awesome 5 Brands" !important;
    }
	.select2-search__field {
		outline-offset: 0;
	}
	.select2-selection {
	    overflow: hidden;
	}
	.select2-selection__rendered[title] {
	    background-color: #ebf0f6;
	    border-color: #ebf0f6;
	}
	.select2-container--default .select2-selection--single {
		border-color: #ebf0f6;
		height: 36px;
		background-color: #ebf0f6;
		padding: .2rem .75rem;
		font-size: initial;
	}
	.select2-container--default .select2-selection--single .select2-selection__rendered {
		color: #77797c;
	}

</style>
@endpush

<select class="form-control select2-icon" name="" data-parsley-errors-container="#selectIcon-errors" required>
	<option value=''>{{__('Select')}}</option>
	<option value='fa-500px'> 500px</option>
	<option value='fa-address-book'> address</option>
	<option value='fa-address-card'> address card</option>
	<option value='fa-adjust'> adjust</option>
	<option value='fa-adn'> adn</option>
	<option value='fa-align-center'> align center</option>
	<option value='fa-align-justify'> align justify</option>
	<option value='fa-align-left'> align left</option>
	<option value='fa-align-right'> align right</option>
	<option value='fa-amazon'> amazon</option>
	<option value='fa-ambulance'> ambulance</option>
	<option value='fa-american-sign-language-interpreting'> american sign language interpreting</option>
	<option value='fa-anchor'> anchor</option>
	<option value='fa-android'> android</option>
	<option value='fa-angellist'> angellist</option>
	<option value='fa-angle-double-down'> angle double down</option>
	<option value='fa-angle-double-left'> angle double left</option>
	<option value='fa-angle-double-right'> angle double right</option>
	<option value='fa-angle-double-up'> angle double up</option>
	<option value='fa-angle-down'> angle down</option>
	<option value='fa-angle-left'> angle left</option>
	<option value='fa-angle-right'> angle right</option>
	<option value='fa-angle-up'> angle up</option>
	<option value='fa-apple'> apple</option>
	<option value='fa-archive'> archive</option>
	<option value='fa-chart-area'> area chart</option>
	<option value='fa-arrow-circle-down'> arrow circle down</option>
	<option value='fa-arrow-circle-left'> arrow circle left</option>
	<option value='fa-arrow-circle-right'> arrow circle right</option>
	<option value='fa-arrow-circle-up'> arrow circle up</option>
	<option value='fa-arrow-down'> arrow down</option>
	<option value='fa-arrow-left'> arrow left</option>
	<option value='fa-arrow-right'> arrow right</option>
	<option value='fa-arrow-up'> arrow up</option>
	<option value='fa-arrows'> arrows</option>
	<option value='fa-arrows-alt'> arrows alt</option>
	<option value='fa-arrows-h'> arrows h</option>
	<option value='fa-arrows-v'> arrows v</option>
	<option value='fa-american-sign-language-interpreting'> asl interpreting</option>
	<option value='fa-assistive-listening-systems'> assistive listening systems</option>
	<option value='fa-asterisk'> asterisk</option>
	<option value='fa-at'> at</option>
	<option value='fa-audio-description'> audio description</option>
	<option value='fa-car'> automobile</option>
	<option value='fa-backward'> backward</option>
	<option value='fa-balance-scale'> balance scale</option>
	<option value='fa-ban'> ban</option>
	<option value='fa-bandcamp'> bandcamp</option>
	<option value='fa-university'> bank</option>
	<option value='fa-chart-bar'> bar chart</option>
	<option value='fa-barcode'> barcode</option>
	<option value='fa-bars'> bars</option>
	<option value='fa-bath'> bath</option>
	<option value='fa-shower'> shower</option>
	<option value='fa-battery-bolt'> battery bolt</option>
	<option value='fa-battery-empty'> battery empty</option>
	<option value='fa-battery-quarter'> battery quarter</option>
	<option value='fa-battery-half'> battery half</option>
	<option value='fa-battery-three-quarters'> battery three quarters</option>
	<option value='fa-battery-full'> battery full</option>
	<option value='fa-bed'> bed</option>
	<option value='fa-beer'> beer</option>
	<option value='fa-behance'> behance</option>
	<option value='fa-behance-square'> behance square</option>
	<option value='fa-bell'> bell</option>
	<option value='fa-bell-slash'> bell slash</option>
	<option value='fa-bicycle'> bicycle</option>
	<option value='fa-binoculars'> binoculars</option>
	<option value='fa-birthday-cake'> birthday cake</option>
	<option value='fa-bitbucket'> bitbucket</option>
	<option value='fa-bitcoin'> bitcoin</option>
	<option value='fa-black-tie'> black tie</option>
	<option value='fa-blind'> blind</option>
	<option value='fa-bluetooth'> bluetooth</option>
	<option value='fa-bluetooth-b'> bluetooth-b</option>
	<option value='fa-bold'> bold</option>
	<option value='fa-bolt'> bolt</option>
	<option value='fa-bomb'> bomb</option>
	<option value='fa-book'> book</option>
	<option value='fa-bookmark'> bookmark</option>
	<option value='fa-braille'> braille</option>
	<option value='fa-briefcase'> briefcase</option>
	<option value='fa-btc'> btc</option>
	<option value='fa-bug'> bug</option>
	<option value='fa-building'> building</option>
	<option value='fa-bullhorn'> bullhorn</option>
	<option value='fa-bullseye'> bullseye</option>
	<option value='fa-bus'> bus</option>
	<option value='fa-buysellads'> buysellads</option>
	<option value='fa-taxi'> taxi</option>
	<option value='fa-calculator'> calculator</option>
	<option value='fa-calendar'> calendar</option>
	<option value='fa-calendar-check'> calendar check</option>
	<option value='fa-calendar-minus'> calendar minus</option>
	<option value='fa-calendar'> calendar</option>
	<option value='fa-calendar-plus'> calendar plus</option>
	<option value='fa-calendar-times'> calendar times</option>
	<option value='fa-camera'> camera</option>
	<option value='fa-camera-retro'> camera retro</option>
	<option value='fa-car'> car</option>
	<option value='fa-caret-down'> caret down</option>
	<option value='fa-caret-left'> caret left</option>
	<option value='fa-caret-right'> caret right</option>
	<option value='fa-caret-square-down'> caret square down</option>
	<option value='fa-caret-square-left'> caret square left</option>
	<option value='fa-caret-square-right'> caret square right</option>
	<option value='fa-caret-square-up'> caret square up</option>
	<option value='fa-caret-up'> caret up</option>
	<option value='fa-cart-arrow-down'> cart arrow down</option>
	<option value='fa-cart-plus'> cart plus</option>
	<option value='fa-closed-captioning'> cc</option>
	<option value='fa-cc-amex'> cc amex</option>
	<option value='fa-cc-diners-club'> cc diners club</option>
	<option value='fa-cc-discover'> cc discover</option>
	<option value='fa-cc-jcb'> cc jcb</option>
	<option value='fa-cc-mastercard'> cc mastercard</option>
	<option value='fa-cc-paypal'> cc paypal</option>
	<option value='fa-cc-stripe'> cc stripe</option>
	<option value='fa-cc-visa'> cc visa</option>
	<option value='fa-certificate'> certificate</option>
	<option value='fa-link'> link</option>
	<option value='fa-unlink'> unlink</option>
	<option value='fa-check'> check</option>
	<option value='fa-check-circle'> check circle</option>
	<option value='fa-check-square'> check square</option>
	<option value='fa-chevron-circle-down'> chevron circle down</option>
	<option value='fa-chevron-circle-left'> chevron-circle left</option>
	<option value='fa-chevron-circle-right'> chevron circle right</option>
	<option value='fa-chevron-circle-up'> chevron circle up</option>
	<option value='fa-chevron-down'> chevron down</option>
	<option value='fa-chevron-left'> chevron left</option>
	<option value='fa-chevron-right'> chevron right</option>
	<option value='fa-chevron-up'> chevron up</option>
	<option value='fa-child'> child</option>
	<option value='fa-chrome'> chrome</option>
	<option value='fa-circle'> circle</option>
	<option value='fa-circle-notch'> circle notch</option>
	<option value='fa-clipboard'> clipboard</option>
	<option value='fa-clock'> clock</option>
	<option value='fa-clone'> clone</option>
	<option value='fa-times'> close</option>
	<option value='fa-window-close'> close window</option>
	<option value='fa-times-hexagon'> close hexagon</option>
	<option value='fa-cloud'> cloud</option>
	<option value='fa-cloud-download'> cloud download</option>
	<option value='fa-cloud-upload'> cloud upload</option>
	<option value='fa-yen-sign'> cny</option>
	<option value='fa-code'> code</option>
	<option value='fa-code-branch'> code fork</option>
	<option value='fa-codepen'> codepen</option>
	<option value='fa-codiepie'> codiepie</option>
	<option value='fa-coffee'> coffee</option>
	<option value='fa-cog'> cog</option>
	<option value='fa-cogs'> cogs</option>
	<option value='fa-columns'> columns</option>
	<option value='fa-comment'> comment</option>
	<option value='fa-comment-alt-dots'> commenting</option>
	<option value='fa-comments'> comments</option>
	<option value='fa-compass'> compass</option>
	<option value='fa-compress'> compress</option>
	<option value='fa-connectdevelop'> connectdevelop</option>
	<option value='fa-contao'> contao</option>
	<option value='fa-copy'> copy</option>
	<option value='fa-copyright'> copyright</option>
	<option value='fa-creative-commons'> creative commons</option>
	<option value='fa-credit-card'> credit card</option>
	<option value='fa-crop'> crop</option>
	<option value='fa-crosshairs'> crosshairs</option>
	<option value='fa-css3'> css3</option>
	<option value='fa-cube'> cube</option>
	<option value='fa-cubes'> cubes</option>
	<option value='fa-cut'> cut</option>
	<option value='fa-tachometer-alt'> dashboard</option>
	<option value='fa-dashcube'> dashcube</option>
	<option value='fa-database'> database</option>
	<option value='fa-deaf'> deaf</option>
	<option value='fa-deaf'> deafness</option>
	<option value='fa-outdent'> dedent</option>
	<option value='fa-delicious'> delicious</option>
	<option value='fa-desktop'> desktop</option>
	<option value='fa-desktop-alt'> desktop-alt</option>
	<option value='fa-deviantart'> deviantart</option>
	<option value='fa-diamond'> diamond</option>
	<option value='fa-digg'> digg</option>
	<option value='fa-dollar-sign'> dollar</option>
	<option value='fa-download'> download</option>
	<option value='fa-dribbble'> dribbble</option>
	<option value='fa-id-card'> drivers license</option>
	<option value='fa-dropbox'> dropbox</option>
	<option value='fa-drupal'> drupal</option>
	<option value='fa-edge'> edge</option>
	<option value='fa-edit'> edit</option>
	<option value='fa-sellcast'> eercast</option>
	<option value='fa-eject'> eject</option>
	<option value='fa-ellipsis-h'> ellipsis h</option>
	<option value='fa-ellipsis-v'> ellipsis v</option>
	<option value='fa-empire'> empire</option>
	<option value='fa-envelope'> envelope</option>
	<option value='fa-envelope-open'> envelope open</option>
	<option value='fa-envelope-square'> envelope square</option>
	<option value='fa-envira'> envira</option>
	<option value='fa-eraser'> eraser</option>
	<option value='fa-etsy'> etsy</option>
	<option value='fa-euro-sign'> euro</option>
	<option value='fa-exchange'> exchange</option>
	<option value='fa-exclamation'> exclamation</option>
	<option value='fa-exclamation-circle'> exclamation circle</option>
	<option value='fa-exclamation-triangle'> exclamation triangle</option>
	<option value='fa-expand'> expand</option>
	<option value='fa-expeditedssl'> expeditedssl</option>
	<option value='fa-external-link'> external link</option>
	<option value='fa-external-link-square'> external link square</option>
	<option value='fa-eye'> eye</option>
	<option value='fa-eye-slash'> eye slash</option>
	<option value='fa-eye-dropper'> eyedropper</option>
	<option value='fa-facebook'> facebook</option>
	<option value='fa-facebook-f'> facebook-f</option>
	<option value='fa-facebook-square'> facebook square</option>
	<option value='fa-facebook-messenger'> facebook messenger</option>
	<option value='fa-fast-backward'> fast backward</option>
	<option value='fa-fast-forward'> fast forward</option>
	<option value='fa-fax'> fax</option>
	<option value='fa-female'> female</option>
	<option value='fa-fighter-jet'> fighter jet</option>
	<option value='fa-file'> file</option>
	<option value='fa-file-archive'> file archive</option>
	<option value='fa-file-audio'> file audio</option>
	<option value='fa-file-code'> file code</option>
	<option value='fa-file-excel'> file excel</option>
	<option value='fa-file-image'> file image</option>
	<option value='fa-file-video'> file video</option>
	<option value='fa-file-pdf'> file pdf</option>
	<option value='fa-file-image'> file photo</option>
	<option value='fa-file-powerpoint'> file powerpoint</option>
	<option value='fa-file-audio'> file sound</option>
	<option value='fa-file-alt'> file text</option>
	<option value='fa-file-video'> file video</option>
	<option value='fa-file-word'> file word</option>
	<option value='fa-file-archive'> file zip</option>
	<option value='fa-film'> film</option>
	<option value='fa-filter'> filter</option>
	<option value='fa-fire'> fire</option>
	<option value='fa-fire-extinguisher'> fire extinguisher</option>
	<option value='fa-firefox'> firefox</option>
	<option value='fa-first-order'> first order</option>
	<option value='fa-flag'> flag</option>
	<option value='fa-flag-checkered'> flag checkered</option>
	<option value='fa-bolt'> flash</option>
	<option value='fa-flask'> flask</option>
	<option value='fa-flickr'> flickr</option>
	<option value='fa-save'> floppy</option>
	<option value='fa-folder'> folder</option>
	<option value='fa-folder-open'> folder open</option>
	<option value='fa-font'> font</option>
	<option value='fa-font-awesome'> font awesome</option>
	<option value='fa-fonticons'> fonticons</option>
	<option value='fa-fort-awesome'> fort awesome</option>
	<option value='fa-forumbee'> forumbee</option>
	<option value='fa-forward'> forward</option>
	<option value='fa-foursquare'> foursquare</option>
	<option value='fa-free-code-camp'> free code camp</option>
	<option value='fa-frown'> frown</option>
	<option value='fa-futbol'> futbol</option>
	<option value='fa-gamepad'> gamepad</option>
	<option value='fa-gavel'> gavel</option>
	<option value='fa-pound-sign'> gbp</option>
	<option value='fa-gem'> gem</option>
	<option value='fa-cog'> gear</option>
	<option value='fa-cogs'> gears</option>
	<option value='fa-genderless'> genderless</option>
	<option value='fa-get-pocket'> get pocket</option>
	<option value='fa-gg'> gg</option>
	<option value='fa-gg-circle'> gg circle</option>
	<option value='fa-gift'> gift</option>
	<option value='fa-git'> git</option>
	<option value='fa-git-square'> git square</option>
	<option value='fa-github'> github</option>
	<option value='fa-github-alt'> github-alt</option>
	<option value='fa-github-square'> github square</option>
	<option value='fa-gitlab'> gitlab</option>
	<option value='fa-gratipay'> gittip</option>
	<option value='fa-glass-champagne'> glass</option>
	<option value='fa-glide'> glide</option>
	<option value='fa-glide-g'> glide-g</option>
	<option value='fa-globe'> globe</option>
	<option value='fa-google'> google</option>
	<option value='fa-google-plus'> google plus</option>
	<option value='fa-google-plus-g'> google plus official</option>
	<option value='fa-google-plus-square'> google plus square</option>
	<option value='fa-google-wallet'> google wallet</option>
	<option value='fa-graduation-cap'> graduation cap</option>
	<option value='fa-gratipay'> gratipay</option>
	<option value='fa-grav'> grav</option>
	<option value='fa-users'> group</option>
	<option value='fa-h-square'> h-square</option>
	<option value='fa-hacker-news'> hacker news</option>
	<option value='fa-hand-rock'> hand grab</option>
	<option value='fa-hand-lizard'> hand lizard</option>
	<option value='fa-hand-point-down'> hand down</option>
	<option value='fa-hand-point-left'> hand left</option>
	<option value='fa-hand-point-right'> hand right</option>
	<option value='fa-hand-point-up'> hand up</option>
	<option value='fa-hand-paper'> hand paper</option>
	<option value='fa-hand-peace'> hand peace</option>
	<option value='fa-hand-pointer'> hand pointer</option>
	<option value='fa-hand-rock'> hand rock</option>
	<option value='fa-hand-scissors'> hand scissors</option>
	<option value='fa-hand-spock'> hand spock</option>
	<option value='fa-hand-paper'> hand stop</option>
	<option value='fa-handshake'> handshake</option>
	<option value='fa-hashtag'> hashtag</option>
	<option value='fa-hdd'> hdd</option>
	<option value='fa-heading'> header</option>
	<option value='fa-headphones'> headphones</option>
	<option value='fa-heart'> heart</option>
	<option value='fa-heartbeat'> heartbeat</option>
	<option value='fa-history'> history</option>
	<option value='fa-home'> home</option>
	<option value='fa-hospital'> hospital</option>
	<option value='fa-hotel'> hotel</option>
	<option value='fa-hourglass'> hourglass</option>
	<option value='fa-hourglass-end'> hourglass end</option>
	<option value='fa-hourglass-half'> hourglass half</option>
	<option value='fa-hourglass-start'> hourglass start</option>
	<option value='fa-houzz'> houzz</option>
	<option value='fa-html5'> html5</option>
	<option value='fa-i-cursor'> i cursor</option>
	<option value='fa-id-badge'> id badge</option>
	<option value='fa-id-card'> id card</option>
	<option value='fa-shekel-sign'> ils</option>
	<option value='fa-image'> image</option>
	<option value='fa-imdb'> imdb</option>
	<option value='fa-inbox'> inbox</option>
	<option value='fa-indent'> indent</option>
	<option value='fa-industry'> industry</option>
	<option value='fa-info'> info</option>
	<option value='fa-info-circle'> info circle</option>
	<option value='fa-rupee-sign'> inr</option>
	<option value='fa-instagram'> instagram</option>
	<option value='fa-internet-explorer'> internet explorer</option>
	<option value='fa-transgender'> intersex</option>
	<option value='fa-ioxhost'> ioxhost</option>
	<option value='fa-italic'> italic</option>
	<option value='fa-joomla'> joomla</option>
	<option value='fa-jsfiddle'> jsfiddle</option>
	<option value='fa-key'> key</option>
	<option value='fa-keyboard'> keyboard</option>
	<option value='fa-krw'> krw</option>
	<option value='fa-language'> language</option>
	<option value='fa-laptop'> laptop</option>
	<option value='fa-lastfm'> lastfm</option>
	<option value='fa-lastfm-square'> lastfm square</option>
	<option value='fa-leaf'> leaf</option>
	<option value='fa-leanpub'> leanpub</option>
	<option value='fa-balance-scale'> legal</option>
	<option value='fa-lemon'> lemon-o</option>
	<option value='fa-level-down'> level down</option>
	<option value='fa-level-up'> level up</option>
	<option value='fa-life-ring'> life ring</option>
	<option value='fa-lightbulb'> lightbulb</option>
	<option value='fa-chart-line'> line chart</option>
	<option value='fa-link'> link</option>
	<option value='fa-linkedin-in'> linkedin</option>
	<option value='fa-linkedin'> linkedin square</option>
	<option value='fa-linode'> linode</option>
	<option value='fa-linux'> linux</option>
	<option value='fa-list'> list</option>
	<option value='fa-list-alt'> list-alt</option>
	<option value='fa-list-ol'> list-ol</option>
	<option value='fa-list-ul'> list-ul</option>
	<option value='fa-location-arrow'> location arrow</option>
	<option value='fa-lock'> lock</option>
	<option value='fa-long-arrow-down'> long arrow down</option>
	<option value='fa-long-arrow-left'> long arrow left</option>
	<option value='fa-long-arrow-right'> long arrow right</option>
	<option value='fa-long-arrow-up'> long arrow up</option>
	<option value='fa-low-vision'> low vision</option>
	<option value='fa-magic'> magic</option>
	<option value='fa-magnet'> magnet</option>
	<option value='fa-paper-plane'> mail send</option>
	<option value='fa-male'> male</option>
	<option value='fa-map'> map</option>
	<option value='fa-map-marker'> map marker</option>
	<option value='fa-map-marker-alt'> map marker alt</option>
	<option value='fa-map-pin'> map pin</option>
	<option value='fa-map-signs'> map signs</option>
	<option value='fa-mars'> mars</option>
	<option value='fa-mars-double'> mars double</option>
	<option value='fa-mars-stroke'> mars stroke</option>
	<option value='fa-mars-stroke-h'> mars stroke h</option>
	<option value='fa-mars-stroke-v'> mars stroke v</option>
	<option value='fa-maxcdn'> maxcdn</option>
	<option value='fa-medium'> medium</option>
	<option value='fa-medkit'> medkit</option>
	<option value='fa-meetup'> meetup</option>
	<option value='fa-meh'> meh</option>
	<option value='fa-mercury'> mercury</option>
	<option value='fa-microchip'> microchip</option>
	<option value='fa-microphone'> microphone</option>
	<option value='fa-microphone-slash'> microphone slash</option>
	<option value='fa-minus'> minus</option>
	<option value='fa-minus-circle'> minus circle</option>
	<option value='fa-minus-square'> minus square</option>
	<option value='fa-mixcloud'> mixcloud</option>
	<option value='fa-mobile'> mobile</option>
	<option value='fa-mobile-alt'> mobile phone</option>
	<option value='fa-modx'> modx</option>
	<option value='fa-money-bill'> money</option>
	<option value='fa-moon'> moon </option>
	<option value='fa-graduation-cap'> graduation cap</option>
	<option value='fa-motorcycle'> motorcycle</option>
	<option value='fa-mouse-pointer'> mouse pointer</option>
	<option value='fa-music'> music</option>
	<option value='fa-bars'> navicon</option>
	<option value='fa-neuter'> neuter</option>
	<option value='fa-newspaper'> newspaper</option>
	<option value='fa-object-group'> object group</option>
	<option value='fa-object-ungroup'> object ungroup</option>
	<option value='fa-odnoklassniki'> odnoklassniki</option>
	<option value='fa-odnoklassniki-square'> odnoklassniki square</option>
	<option value='fa-opencart'> opencart</option>
	<option value='fa-openid'> openid</option>
	<option value='fa-opera'> opera</option>
	<option value='fa-optin-monster'> optin-monster</option>
	<option value='fa-outdent'> outdent</option>
	<option value='fa-pagelines'> pagelines</option>
	<option value='fa-paint-brush'> paint brush</option>
	<option value='fa-paper-plane'> paper plane</option>
	<option value='fa-paperclip'> paperclip</option>
	<option value='fa-paragraph'> paragraph</option>
	<option value='fa-paste'> paste</option>
	<option value='fa-pause'> pause</option>
	<option value='fa-pause-circle'> pause circle</option>
	<option value='fa-paw'> paw</option>
	<option value='fa-paypal'> paypal</option>
	<option value='fa-pencil'> pencil</option>
	<option value='fa-pencil-square'> pencil square</option>
	<option value='fa-percent'> percent</option>
	<option value='fa-phone'> phone</option>
	<option value='fa-phone-alt'> phone alt</option>
	<option value='fa-phone-square'> phone square</option>
	<option value='fa-camera'> camera</option>
	<option value='fa-image'> image</option>
	<option value='fa-chart-pie'> pie chart</option>
	<option value='fa-pied-piper'> pied piper</option>
	<option value='fa-pied-piper-alt'> pied piper alt</option>
	<option value='fa-pied-piper-pp'> pied piper pp</option>
	<option value='fa-pinterest'> pinterest</option>
	<option value='fa-pinterest-p'> pinterest p</option>
	<option value='fa-pinterest-square'> pinterest square</option>
	<option value='fa-plane'> plane</option>
	<option value='fa-play'> play</option>
	<option value='fa-play-circle'> play circle</option>
	<option value='fa-plug'> plug</option>
	<option value='fa-plus'> plus</option>
	<option value='fa-plus-circle'> plus circle</option>
	<option value='fa-plus-square'> plus square</option>
	<option value='fa-podcast'> podcast</option>
	<option value='fa-power-off'> power off</option>
	<option value='fa-print'> print</option>
	<option value='fa-product-hunt'> product hunt</option>
	<option value='fa-puzzle-piece'> puzzle piece</option>
	<option value='fa-qq'> qq</option>
	<option value='fa-qrcode'> qrcode</option>
	<option value='fa-question'> question</option>
	<option value='fa-question-circle'> question circle</option>
	<option value='fa-quora'> quora</option>
	<option value='fa-quote-left'> quote left</option>
	<option value='fa-quote-right'> quote right</option>
	<option value='fa-radio'> radio</option>
	<option value='fa-random'> random</option>
	<option value='fa-ravelry'> ravelry</option>
	<option value='fa-rebel'> rebel</option>
	<option value='fa-recycle'> recycle</option>
	<option value='fa-reddit'> reddit</option>
	<option value='fa-reddit-alien'> reddit alien</option>
	<option value='fa-reddit-square'> reddit square</option>
	<option value='fa-sync'> refresh</option>
	<option value='fa-registered'> registered</option>
	<option value='fa-trash-alt'> remove</option>
	<option value='fa-renren'> renren</option>
	<option value='fa-arrows'> reorder</option>
	<option value='fa-repeat'> repeat</option>
	<option value='fa-reply-all'> reply all</option>
	<option value='fa-hands-helping'> resistance</option>
	<option value='fa-retweet'> retweet</option>
	<option value='fa-road'> road</option>
	<option value='fa-rocket'> rocket</option>
	<option value='fa-ruble-sign'> rouble</option>
	<option value='fa-rss'> rss</option>
	<option value='fa-rss-square'> rss square</option>
	<option value='fa-safari'> safari</option>
	<option value='fa-save'> save</option>
	<option value='fa-cut'> scissors</option>
	<option value='fa-scribd'> scribd</option>
	<option value='fa-search'> search</option>
	<option value='fa-search-minus'> search-minus</option>
	<option value='fa-search-plus'> search-plus</option>
	<option value='fa-sellsy'> sellsy</option>
	<option value='fa-server'> server</option>
	<option value='fa-share'> share</option>
	<option value='fa-share-alt'> share alt</option>
	<option value='fa-share-alt-square'> share alt square</option>
	<option value='fa-share-square'> share square</option>
	<option value='fa-shield'> shield</option>
	<option value='fa-ship'> ship</option>
	<option value='fa-shirtsinbulk'> shirtsinbulk</option>
	<option value='fa-shopping-bag'> shopping bag</option>
	<option value='fa-shopping-basket'> shopping basket</option>
	<option value='fa-shopping-cart'> shopping cart</option>
	<option value='fa-shower'> shower</option>
	<option value='fa-sign-in'> sign in</option>
	<option value='fa-sign-out'> sign out</option>
	<option value='fa-sign-language'> sign language</option>
	<option value='fa-sign-out'> sign out</option>
	<option value='fa-signal'> signal</option>
	<option value='fa-simplybuilt'> simplybuilt</option>
	<option value='fa-sitemap'> sitemap</option>
	<option value='fa-skyatlas'> skyatlas</option>
	<option value='fa-skype'> skype</option>
	<option value='fa-slack'> slack</option>
	<option value='fa-sliders-h'> sliders</option>
	<option value='fa-slideshare'> slideshare</option>
	<option value='fa-smile'> smile</option>
	<option value='fa-snapchat'> snapchat</option>
	<option value='fa-snapchat-ghost'> snapchat ghost</option>
	<option value='fa-snapchat-square'> snapchat square</option>
	<option value='fa-snowflake'> snowflake </option>
	<option value='fa-futbol'> soccer ball</option>
	<option value='fa-sort'> sort</option>
	<option value='fa-sort-alpha-down'> sort alpha asc</option>
	<option value='fa-sort-alpha-up'> sort alpha desc</option>
	<option value='fa-sort-up'> sort up</option>
	<option value='fa-sort-down'> sort down</option>
	<option value='fa-sort-numeric-down-alt'> sort numeric asc</option>
	<option value='fa-sort-numeric-up-alt'> sort numeric desc</option>
	<option value='fa-sort-up'> sort up</option>
	<option value='fa-soundcloud'> soundcloud</option>
	<option value='fa-space-shuttle'> space shuttle</option>
	<option value='fa-spinner'> spinner</option>
	<option value='fa-spotify'> spotify</option>
	<option value='fa-square'> square</option>
	<option value='fa-stack-exchange'> stack exchange</option>
	<option value='fa-stack-overflow'> stack overflow</option>
	<option value='fa-star'> star</option>
	<option value='fa-star-half'> star half</option>
	<option value='fa-steam'> steam</option>
	<option value='fa-steam-square'> steam square</option>
	<option value='fa-step-backward'> step backward</option>
	<option value='fa-step-forward'> step forward</option>
	<option value='fa-stethoscope'> stethoscope</option>
	<option value='fa-sticky-note'> sticky note</option>
	<option value='fa-stop'> stop</option>
	<option value='fa-stop-circle'> stop circle</option>
	<option value='fa-street-view'> street view</option>
	<option value='fa-strikethrough'> strikethrough</option>
	<option value='fa-stumbleupon'> stumbleupon</option>
	<option value='fa-stumbleupon-circle'> stumbleupon circle</option>
	<option value='fa-subscript'> subscript</option>
	<option value='fa-subway'> subway</option>
	<option value='fa-suitcase'> suitcase</option>
	<option value='fa-sun'> sun</option>
	<option value='fa-superpowers'> superpowers</option>
	<option value='fa-superscript'> superscript</option>
	<option value='fa-headset'> support</option>
	<option value='fa-table'> table</option>
	<option value='fa-tablet'> tablet</option>
	<option value='fa-tachometer'> tachometer</option>
	<option value='fa-tag'> tag</option>
	<option value='fa-tags'> tags</option>
	<option value='fa-tasks'> tasks</option>
	<option value='fa-taxi'> taxi</option>
	<option value='fa-telegram'> telegram</option>
	<option value='fa-tv-retro'> television</option>
	<option value='fa-tencent-weibo'> tencent-weibo</option>
	<option value='fa-terminal'> terminal</option>
	<option value='fa-text-height'> text-height</option>
	<option value='fa-text-width'> text-width</option>
	<option value='fa-th'> th</option>
	<option value='fa-th-large'> th-large</option>
	<option value='fa-th-list'> th-list</option>
	<option value='fa-themeisle'> themeisle</option>
	<option value='fa-thermometer-full'> thermometer</option>
	<option value='fa-thermometer-quarter'> thermometer quarter</option>
	<option value='fa-thermometer-half'> thermometer half</option>
	<option value='fa-thermometer-three-quarters'> thermometer three quarters</option>
	<option value='fa-thermometer-empty'> thermometer empty</option>
	<option value='fa-thumb-thumbtack'> thumb tack</option>
	<option value='fa-thumbs-down'> thumbs down</option>
	<option value='fa-thumbs-up'> thumbs-up</option>
	<option value='fa-ticket'> ticket</option>
	<option value='fa-times'> times</option>
	<option value='fa-times-circle'> times circle</option>
	<option value='fa-times-rectangle'> times rectangle</option>
	<option value='fa-tint'> tint</option>
	<option value='fa-toggle-off'> toggle off</option>
	<option value='fa-toggle-on'> toggle on</option>
	<option value='fa-trademark'> trademark</option>
	<option value='fa-train'> train</option>
	<option value='fa-transgender'> transgender</option>
	<option value='fa-transgender-alt'> transgender-alt</option>
	<option value='fa-trash'> trash</option>
	<option value='fa-tree'> tree</option>
	<option value='fa-trello'> trello</option>
	<option value='fa-tripadvisor'> tripadvisor</option>
	<option value='fa-trophy'> trophy</option>
	<option value='fa-truck'> truck</option>
	<option value='fa-tty'> tty</option>
	<option value='fa-tumblr'> tumblr</option>
	<option value='fa-tumblr-square'> tumblr-square</option>
	<option value='fa-tv'> tv</option>
	<option value='fa-twitch'> twitch</option>
	<option value='fa-twitter'> twitter</option>
	<option value='fa-twitter-square'> twitter-square</option>
	<option value='fa-umbrella'> umbrella</option>
	<option value='fa-underline'> underline</option>
	<option value='fa-undo'> undo</option>
	<option value='fa-universal-access'> universal-access</option>
	<option value='fa-university'> university</option>
	<option value='fa-unlink'> unlink</option>
	<option value='fa-unlock'> unlock</option>
	<option value='fa-unlock-alt'> unlock-alt</option>
	<option value='fa-upload'> upload</option>
	<option value='fa-usb'> usb</option>
	<option value='fa-user'> user</option>
	<option value='fa-user-circle'> user-circle</option>
	<option value='fa-user-circle'> user circle</option>
	<option value='fa-user-md'> user-md</option>
	<option value='fa-user-alt-slash'> user slash</option>
	<option value='fa-user-check'> user check</option>
	<option value='fa-user-plus'> user plus</option>
	<option value='fa-user-secret'> user secret</option>
	<option value='fa-user-times'> user times</option>
	<option value='fa-users'> users</option>
	<option value='fa-venus'> venus</option>
	<option value='fa-venus-double'> venus-double</option>
	<option value='fa-venus-mars'> venus mars</option>
	<option value='fa-viacoin'> viacoin</option>
	<option value='fa-viadeo'> viadeo</option>
	<option value='fa-viadeo-square'> viadeo square</option>
	<option value='fa-vimeo'> vimeo</option>
	<option value='fa-vimeo-square'> vimeo square</option>
	<option value='fa-vine'> vine</option>
	<option value='fa-vk'> vk</option>
	<option value='fa-phone-volume'> volume control phone</option>
	<option value='fa-volume-down'> volume down</option>
	<option value='fa-volume-off'> volume off</option>
	<option value='fa-volume-up'> volume up</option>
	<option value='fa-exclamation-triangle'> warning</option>
	<option value='fa-weixin'> wechat</option>
	<option value='fa-weibo'> weibo</option>
	<option value='fa-weixin'> weixin</option>
	<option value='fa-whatsapp'> whatsapp</option>
	<option value='fa-wheelchair'> wheelchair</option>
	<option value='fa-wifi'> wifi</option>
	<option value='fa-wikipedia-w'> wikipedia w</option>
	<option value='fa-window-close'> window close</option>
	<option value='fa-window-maximize'> window maximize</option>
	<option value='fa-window-minimize'> window minimize</option>
	<option value='fa-window-restore'> window restore</option>
	<option value='fa-windows'> windows</option>
	<option value='fa-won-sign'> won</option>
	<option value='fa-wordpress'> wordpress</option>
	<option value='fa-wpbeginner'> wpbeginner</option>
	<option value='fa-wpexplorer'> wpexplorer</option>
	<option value='fa-wpforms'> wpforms</option>
	<option value='fa-wrench'> wrench</option>
	<option value='fa-xing'> xing</option>
	<option value='fa-xing-square'> xing square</option>
	<option value='fa-y-combinator'> y combinator</option>
	<option value='fa-yahoo'> yahoo</option>
	<option value='fa-yelp'> yelp</option>
	<option value='fa-yoast'> yoast</option>
	<option value='fa-youtube'> youtube</option>
	<option value='fa-play'> youtube play</option>
	<option value='fa-youtube-square'> youtube square</option>
	<option value='fa-brain'> brain</option>
	<option value='fa-shield-check'> shield check</option>
	<option value='fa-globe-americas'> globe americas</option>
	<option value='fa-file-signature'> file signature</option>
</select>
<div style="margin-bottom: 20px;" id="selectIcon-errors"></div>

@push('js')
<script src="{{asset('assets/admin')}}/plugins/select2/js/select2.full.min.js"></script>
<script src="{{asset('assets/admin')}}/plugins/select2/js/i18n/{{ app()->getLocale() }}.js"></script>

{{-- 
<script type="text/javascript">
	$('select#{{$val}}').val('{{$val}}');
</script>
 --}}
<script type="text/javascript">
	window.initSelect2Drop=()=>{
		function formatText (icon) {
		    return $('<span><i class="fas ' + $(icon.element).val() + '"></i> ' + icon.text + '</span>');
		};

		$('.select2-icon').select2({
		    width: "100%",
		    templateSelection: formatText,
		    templateResult: formatText
		});
	};

	$(document).ready(function(){
        initSelect2Drop();
    });
</script>
@endpush
